# Generated by Django 4.2.3 on 2023-10-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('country_code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_date', models.DateField(auto_created=True, auto_now_add=True)),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_contact', models.PositiveIntegerField(unique=True)),
                ('owner_city', models.CharField(default='Bengaluru', max_length=30)),
                ('owner_state', models.CharField(default='Karnataka', max_length=30)),
                ('owner_country', models.CharField(default='India', max_length=30)),
                ('owner_contact_prefix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets_app.countrymodel')),
            ],
        ),
        migrations.CreateModel(
            name='PetServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_created=True, auto_now_add=True)),
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('service_required', models.CharField(choices=[('Grooming', 'Grooming'), ('Consultation', 'Consultation'), ('BothBoth', 'Both')], default='Consultation', max_length=20)),
                ('grooming_type', models.CharField(blank=True, choices=[('Hair Cutting', 'Hair Cutting'), ('Hair Cleaning', 'Hair Cleaning'), ('Body Wash', 'Body Wash'), ('Nail Cleaning', 'Nail Cleaning'), ('Nail Cutting', 'Nail Cutting')], max_length=20)),
                ('consultation_type', models.CharField(blank=True, choices=[('Doctor 1', 'Doctor 1'), ('Doctor 2', 'Doctor 2'), ('Doctor 3', 'Doctor 3'), ('Doctor 4', 'Doctor 4')], max_length=20)),
                ('pet_name', models.CharField(blank=True, max_length=10)),
                ('contact', models.PositiveIntegerField(blank=True)),
                ('id_2', models.PositiveBigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('pet_type', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Horse', 'Horse'), ('Rabbit', 'Rabbit'), ('Pigeon', 'Pigeon')], default='Cat', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('breed', models.CharField(choices=[('German_Shephard', 'German_Shephard'), ('Labrador', 'Labrador'), ('Indie', 'Indie'), ('Persian', 'Persian')], default='Indie', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Unknown', 'Unknown')], default='M', max_length=7)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets_app.ownermodel', to_field='owner_contact')),
            ],
        ),
    ]
