# Generated by Django 4.2.3 on 2023-10-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0002_alter_petinformation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petservices',
            name='contact',
        ),
    ]
