# Generated by Django 4.2.3 on 2023-10-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0003_remove_petservices_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='petservices',
            name='created_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='petservices',
            name='updated_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
