# Generated by Django 4.2.3 on 2023-10-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0004_petservices_created_by_petservices_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownermodel',
            name='created_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ownermodel',
            name='updated_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='petinformation',
            name='created_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='petinformation',
            name='updated_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
